name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot || echo "Remote already exists"

      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          git push --force https://huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot main
          exit 0
