name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Fetch only the root files
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            images
            README.md
            Dockerfile
            requirements.txt
          fetch-depth: 0

      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://nikhilkomakula:$HF_TOKEN@huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot || true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://nikhilkomakula:$HF_TOKEN@huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot main
          exit 0
