name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:

      - name: LFS Install
        run: git lfs install
      
      - name: LFS Track
        run: git lfs track "data/9.0 administrators_guide.pdf" && git lfs track "indexes/chroma.sqlite3"
      
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          git remote add space https://nikhilkomakula:${{ secrets.HUGGINGFACEHUB_API_TOKEN }}@huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot || true

      - name: Push to hub
        env:
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          git push --force https://nikhilkomakula:${{ secrets.HUGGINGFACEHUB_API_TOKEN }}@huggingface.co/spaces/nikhilkomakula/llm-rag-op-chatbot main
          exit 0
